spring:
  application:
    name: email-service
  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true
        hostname: host.docker.internal
  mail:
    host: ${EMAIL_HOST:587}
    port: ${EMAIL_PORT:smtp.gmail.com}
    username: ${EMAIL_USERNAME:fcarpio113@gmail.com}
    password: ${EMAIL_PASSWORD:qfqdqzqwbanlligl}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        timeout: 5000
management:
  metrics:
    tags:
      application: email-service
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
  server:
    port: 8150
server:
  port: 8150