spring:
  application:
    name: security-service
  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true
        hostname: host.docker.internal
server:
  port: 8090

management:
  metrics:
    tags:
      application: security-service
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
  server:
    port: 8090

jwt:
  time:
    expiration: 86400000  # 1 dia en milisegundos